# Generated by Django 5.0.6 on 2024-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reyting',
            field=models.FloatField(default=0),
        ),
    ]
